
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
target ‘PrinterDemo’ do
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'SnapKit'
pod 'HMSegmentedControl'
pod 'Then'
pod 'Reusable'

end
